// Canonical menu specification for 7 Spices Restaurant.
// Used to reconcile categories/items with the cloud database:
// - Missing categories/items are CREATED
// - Existing categories/items (matched case-insensitively by name)
//   are UPDATED (price / veg flag / category assignment)
// - Anything in the DB that is not in this spec is DELETED
//
// Update this file whenever the master menu changes and click
// "Sync Menu from Master List" in Settings → Database Tools.

export interface SpecItem {
  name: string;
  price: number;
  veg: boolean;
  isBengali?: boolean;
}
export interface SpecCategory {
  name: string;
  items: SpecItem[];
}

const chineseRiceTable = (base: string) => [
  { name: `Veg ${base}`, price: 0, veg: true },
  { name: `Chicken ${base}`, price: 0, veg: false },
  { name: `Mix ${base}`, price: 0, veg: false },
];

export const MENU_SPEC: SpecCategory[] = [
  {
    name: "Soup Sensation",
    items: [
      { name: "Clear Soup Veg", price: 120, veg: true },
      { name: "Clear Soup Non-Veg", price: 140, veg: false },
      { name: "Manchow Soup Veg", price: 130, veg: true },
      { name: "Manchow Soup Non-Veg", price: 160, veg: false },
      { name: "Sweet Corn Soup Veg", price: 120, veg: true },
      { name: "Sweet Corn Soup Non-Veg", price: 150, veg: false },
      { name: "Hot & Sour Soup Veg", price: 130, veg: true },
      { name: "Hot & Sour Soup Non-Veg", price: 160, veg: false },
      { name: "Lemon Coriander Soup Veg", price: 130, veg: true },
      { name: "Lemon Coriander Soup Non-Veg", price: 160, veg: false },
      { name: "Cream of Mushroom Soup", price: 150, veg: true },
      { name: "7 Spices Special Soup Veg", price: 140, veg: true },
      { name: "7 Spices Special Soup Non-Veg", price: 170, veg: false },
    ],
  },
  {
    name: "Veg Starter",
    items: [
      { name: "Crispy Chilli Baby Corn", price: 260, veg: true },
      { name: "Chilli Mushroom", price: 270, veg: true },
      { name: "Baby Corn with Mushroom Chilli", price: 280, veg: true },
      { name: "Crispy Chilli Potato", price: 210, veg: true },
      { name: "Honey Chilli Potato", price: 220, veg: true },
      { name: "Paneer 65 Dry (8 pcs)", price: 280, veg: true },
      { name: "Chilli Paneer Dry (8 pcs)", price: 280, veg: true },
      { name: "Paneer Manchurian Dry (8 pcs)", price: 280, veg: true },
      { name: "Paneer Pakora (6 pcs)", price: 260, veg: true },
      { name: "Crispy Chilli Paneer", price: 270, veg: true },
      { name: "American Corn Salt & Pepper", price: 270, veg: true },
      { name: "Pepper Mushroom", price: 280, veg: true },
      { name: "Crispy Fried Paneer", price: 280, veg: true },
    ],
  },
  {
    name: "Non-Veg Starter",
    items: [
      { name: "Chicken Drumstick (6 pcs)", price: 280, veg: false },
      { name: "Chicken Lollipop (6 pcs)", price: 270, veg: false },
      { name: "Chilli Chicken Dry (8 pcs)", price: 280, veg: false },
      { name: "Chicken Manchurian Dry (8 pcs)", price: 280, veg: false },
      { name: "Chicken 65 Dry (8 pcs)", price: 280, veg: false },
      { name: "Pan Fried Chilli Chicken (6 pcs)", price: 300, veg: false },
      { name: "Chicken Salt & Pepper (8 pcs)", price: 290, veg: false },
      { name: "Crispy Chicken", price: 280, veg: false },
      { name: "Dragon Chicken (8 pcs)", price: 280, veg: false },
      { name: "Tangra Chilli Chicken", price: 280, veg: false },
      { name: "Honey Chicken", price: 290, veg: false },
      { name: "Chicken Red Chilli (8 pcs)", price: 280, veg: false },
      { name: "Chicken Pakora (6 pcs)", price: 270, veg: false },
      { name: "Chilli Fish Dry (8 pcs)", price: 300, veg: false },
      { name: "Pan Fried Chilli Fish (6 pcs)", price: 320, veg: false },
      { name: "Fish Fry (1 pc)", price: 190, veg: false },
      { name: "Fish Finger (6 pcs)", price: 310, veg: false },
      { name: "Fish Pakora (6 pcs)", price: 270, veg: false },
      { name: "Fish & Chips (6 pcs)", price: 320, veg: false },
      { name: "Chilli Prawn Dry (6 pcs)", price: 330, veg: false },
      { name: "Prawn Manchurian Dry (6 pcs)", price: 370, veg: false },
      { name: "Prawn 65 Dry (6 pcs)", price: 375, veg: false },
      { name: "Golden Fried Prawn (6 pcs)", price: 385, veg: false },
      { name: "Crispy Fried Prawn (6 pcs)", price: 370, veg: false },
    ],
  },
  {
    name: "Grill Garden",
    items: [
      { name: "Tandoori Chicken (Half)", price: 260, veg: false },
      { name: "Tandoori Chicken (Full)", price: 460, veg: false },
      { name: "Chicken Tikka (6 pcs)", price: 300, veg: false },
      { name: "Alishan Tikka", price: 320, veg: false },
      { name: "Afgani Tikka", price: 340, veg: false },
      { name: "Reshmi Kabab", price: 300, veg: false },
      { name: "Malai Kabab", price: 330, veg: false },
      { name: "Pahari Kabab", price: 320, veg: false },
      { name: "Lasuni Tikka", price: 320, veg: false },
      { name: "Fish Tikka (4 pcs)", price: 340, veg: false },
      { name: "Fish Ajwani Tikka (4 pcs)", price: 350, veg: false },
      { name: "Mahi Afgani (4 pcs)", price: 350, veg: false },
      { name: "Paneer Tikka (6 pcs)", price: 320, veg: true },
      { name: "Mushroom Tikka (8 pcs)", price: 280, veg: true },
      { name: "Achari Paneer Tikka", price: 330, veg: true },
      { name: "Paneer Malai Tikka", price: 330, veg: true },
    ],
  },
  {
    name: "Sizzler",
    items: [
      { name: "Chinese Sizzler", price: 430, veg: true },
      { name: "BBQ Chicken Sizzler", price: 450, veg: false },
    ],
  },
  {
    name: "Indian Breads",
    items: [
      { name: "Tandoori Roti", price: 30, veg: true },
      { name: "Butter Tandoori Roti", price: 39, veg: true },
      { name: "Plain Naan", price: 50, veg: true },
      { name: "Butter Naan", price: 65, veg: true },
      { name: "Masala Kulcha", price: 90, veg: true },
      { name: "Paneer Kulcha", price: 100, veg: true },
      { name: "Laccha Paratha", price: 70, veg: true },
      { name: "Garlic Naan", price: 75, veg: true },
      { name: "Cheese Naan", price: 85, veg: true },
      { name: "Cheese Chilli Garlic Naan", price: 110, veg: true },
      { name: "Keema Kulcha", price: 129, veg: false },
      { name: "Amritsari Kulcha", price: 110, veg: true },
      { name: "Aloo Kulcha", price: 80, veg: true },
    ],
  },
  {
    name: "Indian Rice",
    items: [
      { name: "Steamed Rice", price: 110, veg: true },
      { name: "Jeera Rice", price: 150, veg: true },
      { name: "Peas Pulao", price: 160, veg: true },
      { name: "Veg Pulao", price: 180, veg: true },
      { name: "Kashmiri Pulao", price: 210, veg: true },
      { name: "Mutton Keema Rice", price: 300, veg: false },
      { name: "Nabratan Pulao", price: 190, veg: true },
    ],
  },
  {
    name: "Biriyani",
    items: [
      { name: "Chicken Biriyani", price: 210, veg: false },
      { name: "Mutton Biriyani", price: 260, veg: false },
      { name: "Hyderabadi Biriyani", price: 220, veg: false },
      { name: "Kolapuri Biriyani", price: 240, veg: false },
    ],
  },
  {
    name: "Chinese Rice",
    items: [
      { name: "Veg Fried Rice", price: 190, veg: true },
      { name: "Egg Fried Rice", price: 220, veg: false },
      { name: "Chicken Fried Rice", price: 240, veg: false },
      { name: "Mix Fried Rice", price: 260, veg: false },
      { name: "Veg Garlic Fried Rice", price: 200, veg: true },
      { name: "Chicken Garlic Fried Rice", price: 250, veg: false },
      { name: "Mix Garlic Fried Rice", price: 270, veg: false },
      { name: "Veg Chilli Garlic Fried Rice", price: 210, veg: true },
      { name: "Chicken Chilli Garlic Fried Rice", price: 260, veg: false },
      { name: "Mix Chilli Garlic Fried Rice", price: 280, veg: false },
      { name: "Veg Hong Kong Fried Rice", price: 210, veg: true },
      { name: "Chicken Hong Kong Fried Rice", price: 260, veg: false },
      { name: "Mix Hong Kong Fried Rice", price: 280, veg: false },
      { name: "Veg Singapore Fried Rice", price: 210, veg: true },
      { name: "Chicken Singapore Fried Rice", price: 260, veg: false },
      { name: "Mix Singapore Fried Rice", price: 280, veg: false },
      { name: "Veg Schezwan Fried Rice", price: 200, veg: true },
      { name: "Chicken Schezwan Fried Rice", price: 250, veg: false },
      { name: "Mix Schezwan Fried Rice", price: 270, veg: false },
      { name: "Veg Shanghai Fried Rice", price: 210, veg: true },
      { name: "Chicken Shanghai Fried Rice", price: 260, veg: false },
      { name: "Mix Shanghai Fried Rice", price: 280, veg: false },
    ],
  },
  {
    name: "Noodles",
    items: [
      { name: "Veg Hakka", price: 180, veg: true },
      { name: "Egg Hakka", price: 210, veg: false },
      { name: "Chicken Hakka", price: 230, veg: false },
      { name: "Mix Hakka", price: 250, veg: false },
      { name: "Veg Pan Fried Noodles", price: 190, veg: true },
      { name: "Chicken Pan Fried Noodles", price: 230, veg: false },
      { name: "Mix Pan Fried Noodles", price: 260, veg: false },
      { name: "Veg Gravy Noodles", price: 200, veg: true },
      { name: "Chicken Gravy Noodles", price: 240, veg: false },
      { name: "Mix Gravy Noodles", price: 270, veg: false },
      { name: "Veg Schezwan Hakka", price: 210, veg: true },
      { name: "Chicken Schezwan Hakka", price: 250, veg: false },
      { name: "Mix Schezwan Hakka", price: 280, veg: false },
    ],
  },
  {
    name: "Chinese Veg Side Dish",
    items: [
      { name: "Chilli Paneer", price: 300, veg: true },
      { name: "Paneer Manchurian", price: 300, veg: true },
      { name: "Paneer 65", price: 310, veg: true },
      { name: "Chilli Mushroom (Gravy)", price: 290, veg: true },
      { name: "Paneer Sweet & Sour", price: 310, veg: true },
      { name: "Paneer Hot Garlic", price: 300, veg: true },
      { name: "Veg Manchurian", price: 280, veg: true },
    ],
  },
  {
    name: "Chinese Non-Veg Side Dish",
    items: [
      { name: "Chilli Chicken", price: 300, veg: false },
      { name: "Chicken Manchurian", price: 300, veg: false },
      { name: "Chicken 65", price: 310, veg: false },
      { name: "Chicken Hot Garlic", price: 300, veg: false },
      { name: "Schezwan Chicken", price: 310, veg: false },
      { name: "Garlic Chicken", price: 300, veg: false },
      { name: "Lemon Chicken", price: 310, veg: false },
      { name: "Kung Pao Chicken", price: 320, veg: false },
      { name: "Chicken Sweet & Sour", price: 320, veg: false },
      { name: "Ginger Chicken", price: 310, veg: false },
      { name: "Hunan Chicken", price: 310, veg: false },
    ],
  },
  {
    name: "Prawns",
    items: [
      { name: "Prawn Masala", price: 375, veg: false },
      { name: "Prawn Malai Curry", price: 390, veg: false },
      { name: "Prawn Do-Piyaza", price: 375, veg: false },
      { name: "Prawn Tikka Masala", price: 400, veg: false },
      { name: "Prawn Kadai", price: 360, veg: false },
      { name: "Prawn Curry", price: 360, veg: false },
    ],
  },
  {
    name: "Chicken Corner",
    items: [
      { name: "Chicken Kosha", price: 280, veg: false },
      { name: "Chicken Curry", price: 270, veg: false },
      { name: "Chicken Masala", price: 290, veg: false },
      { name: "Chicken Do-Piyaza", price: 310, veg: false },
      { name: "Chicken Korma", price: 330, veg: false },
      { name: "Chicken Punjabi", price: 310, veg: false },
      { name: "Chicken Jhalfrezi", price: 320, veg: false },
      { name: "Chicken Handi", price: 380, veg: false },
      { name: "Chicken Rara", price: 330, veg: false },
      { name: "Chicken Lahori", price: 320, veg: false },
      { name: "Chicken Dakbanglo", price: 340, veg: false },
      { name: "Chicken Bharta", price: 290, veg: false },
      { name: "Chicken Keema", price: 290, veg: false },
      { name: "Chicken Kadai (4 pcs)", price: 320, veg: false },
      { name: "Chicken Kadai (6 pcs B/L)", price: 350, veg: false },
      { name: "Murgh Angara", price: 330, veg: false },
      { name: "Chicken Kali Mirch", price: 330, veg: false },
      { name: "Chicken Reshmi Masala", price: 340, veg: false },
      { name: "Chicken Reshmi Butter Masala", price: 360, veg: false },
      { name: "Chicken Tikka Masala", price: 340, veg: false },
      { name: "Chicken Tikka Butter Masala", price: 350, veg: false },
      { name: "Butter Chicken", price: 360, veg: false },
      { name: "Chicken Afgani", price: 330, veg: false },
      { name: "Chicken Bhuna", price: 320, veg: false },
      { name: "Chicken Akhrai", price: 340, veg: false },
    ],
  },
  {
    name: "Mutton Paradise",
    items: [
      { name: "Laal Maas", price: 450, veg: false },
      { name: "Mutton Curry", price: 380, veg: false },
      { name: "Mutton Kosha", price: 410, veg: false },
      { name: "Mutton Masala", price: 410, veg: false },
      { name: "Mutton Do-Piyaza", price: 410, veg: false },
      { name: "Mutton Kadai", price: 410, veg: false },
      { name: "Mutton Lahori", price: 430, veg: false },
      { name: "Mutton Dakbanglo", price: 450, veg: false },
      { name: "Mutton Korma", price: 440, veg: false },
      { name: "Mutton Bhuna", price: 430, veg: false },
    ],
  },
  {
    name: "Veggie Paradise",
    items: [
      { name: "Yellow Dal Fry", price: 150, veg: true },
      { name: "Dal Makhani", price: 180, veg: true },
      { name: "Mix Veg", price: 260, veg: true },
      { name: "Veg Jhalfrezi", price: 280, veg: true },
      { name: "Mushroom Masala", price: 270, veg: true },
      { name: "Paneer Do-Piyaza (6 pcs)", price: 290, veg: true },
      { name: "Veg Keema Kasturi", price: 280, veg: true },
      { name: "Veg Punjabi", price: 280, veg: true },
      { name: "Paneer Butter Masala (Jain)", price: 300, veg: true },
      { name: "Paneer Butter Masala", price: 290, veg: true },
      { name: "Paneer Tikka Masala (6 pcs)", price: 340, veg: true },
      { name: "Palak Paneer", price: 290, veg: true },
      { name: "Paneer Punjabi (6 pcs)", price: 300, veg: true },
      { name: "Matar Paneer", price: 270, veg: true },
      { name: "Kadai Paneer (6 pcs)", price: 310, veg: true },
      { name: "Aloo Jeera", price: 180, veg: true },
      { name: "Aloo Dum Kashmiri (6 pcs)", price: 210, veg: true },
      { name: "Aloo Dum Banarasi (6 pcs)", price: 190, veg: true },
      { name: "Aloo Do-Piyaza (6 pcs)", price: 190, veg: true },
    ],
  },
  {
    name: "Fish",
    items: [
      { name: "Fish Masala", price: 310, veg: false },
      { name: "Fish Do-Piyaza", price: 320, veg: false },
      { name: "Fish Tikka Masala", price: 360, veg: false },
      { name: "Fish Tikka Butter Masala", price: 380, veg: false },
      { name: "Fish Tawa Masala", price: 340, veg: false },
      { name: "Fish Punjabi", price: 340, veg: false },
      { name: "Fish Chilli", price: 310, veg: false },
      { name: "Fish Manchurian", price: 310, veg: false },
      { name: "Garlic Fish", price: 310, veg: false },
      { name: "Fish Hot Garlic", price: 310, veg: false },
      { name: "Fish 65", price: 320, veg: false },
    ],
  },
  {
    name: "Salad",
    items: [
      { name: "Green Salad", price: 80, veg: true },
      { name: "Onion Salad", price: 70, veg: true },
      { name: "Papad", price: 50, veg: true },
      { name: "Masala Papad", price: 70, veg: true },
    ],
  },
  {
    name: "Combo",
    items: [
      { name: "Chilli Chicken (2 pcs) + Veg Fried Rice + Salad", price: 149, veg: false },
      { name: "Chilli Chicken (2 pcs) + Veg Hakka + Salad", price: 149, veg: false },
      { name: "Chicken Kosha (2 pcs) + Chicken Biriyani + Salad", price: 210, veg: false },
      { name: "Chicken Do-Piyaza (2 pcs) + Laccha Paratha + Salad", price: 210, veg: false },
      { name: "Chilli Fish (2 pcs) + Veg Fried Rice + Salad", price: 199, veg: false },
      { name: "Fish 65 (2 pcs) + Veg Hakka + Salad", price: 199, veg: false },
      { name: "Chicken Curry (2 pcs) + Steamed Rice + Salad", price: 189, veg: false },
      { name: "Chicken Masala (2 pcs) + Jeera Rice + Salad", price: 189, veg: false },
      { name: "Chilli Paneer (4 pcs) + Veg Hakka + Salad", price: 179, veg: true },
      { name: "Chilli Paneer (4 pcs) + Veg Fried Rice + Salad", price: 179, veg: true },
      { name: "Paneer Kadai (4 pcs) + Butter Naan + Salad", price: 229, veg: true },
      { name: "Paneer Butter Masala + Tandoori Roti (2 pcs) + Salad", price: 219, veg: true },
      { name: "Mutton Kosha (2 pcs) + Butter Naan (2 pcs) + Peas Pulao + Salad", price: 299, veg: false },
    ],
  },
  {
    name: "Mocktail",
    items: [
      { name: "Cold Drinks", price: 40, veg: true },
      { name: "Masala Cold Drinks", price: 70, veg: true },
      { name: "Fresh Lime Soda", price: 70, veg: true },
      { name: "Virgin Mojito", price: 110, veg: true },
      { name: "Blue Lagoon", price: 100, veg: true },
      { name: "Kiwi Mojito", price: 120, veg: true },
      { name: "Mojito Variety", price: 130, veg: true },
      { name: "Cold Coffee", price: 150, veg: true },
      { name: "Milk Shake", price: 150, veg: true },
      { name: "Oreo Shake", price: 150, veg: true },
      { name: "Pink Lady", price: 120, veg: true },
      { name: "Orange Blossom", price: 150, veg: true },
      { name: "Spicy Tango", price: 130, veg: true },
      { name: "Barman Special Mocktail", price: 160, veg: true },
    ],
  },
  {
    name: "Dessert",
    items: [
      { name: "Gajar Ka Halua", price: 130, veg: true },
      { name: "Gulab Jamun", price: 80, veg: true },
      { name: "Hot Gulab Jamun with Ice Cream", price: 130, veg: true },
      { name: "Brownie with Ice Cream", price: 180, veg: true },
      { name: "Ice Cream", price: 90, veg: true },
    ],
  },
  {
    name: "Thali",
    items: [
      { name: "Veg Thali", price: 159, veg: true },
      { name: "Fish Thali", price: 209, veg: false },
      { name: "Chicken Thali", price: 249, veg: false },
      { name: "Mutton Thali", price: 349, veg: false },
    ],
  },
  {
    name: "Bengali",
    items: [
      { name: "Rui Posto", price: 150, veg: false, isBengali: true },
      { name: "Doi Katla", price: 160, veg: false, isBengali: true },
      { name: "Rui Kalia", price: 110, veg: false, isBengali: true },
      { name: "Katla Kalia", price: 140, veg: false, isBengali: true },
      { name: "Pabda Kalia", price: 170, veg: false, isBengali: true },
      { name: "Rui Jhalda", price: 120, veg: false, isBengali: true },
      { name: "Katla Jhalda", price: 160, veg: false, isBengali: true },
      { name: "Pomfret Jhalda", price: 250, veg: false, isBengali: true },
      { name: "Pabda Jhalda", price: 180, veg: false, isBengali: true },
      { name: "Rui Mach Vaja", price: 100, veg: false, isBengali: true },
      { name: "Katla Mach Vaja", price: 120, veg: false, isBengali: true },
      { name: "Pomfret Mach Vaja", price: 210, veg: false, isBengali: true },
      { name: "Posto Bora (2 pcs)", price: 170, veg: true, isBengali: true },
      { name: "Home Style Chicken", price: 290, veg: false, isBengali: true },
      { name: "Home Style Mutton", price: 400, veg: false, isBengali: true },
    ],
  },
];

// Unused helper kept for reference (silence lint).
void chineseRiceTable;
